services:
  pg:
    image: postgres:13.22-alpine3.21
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - pg
    container_name: widget-server
    ports:
      - '3000:3000'
    environment:
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUFLARE_BUCKET=$CLOUFLARE_BUCKET
      - CLOUFLARE_PUBLIC_URL=$CLOUFLARE_PUBLIC_URL
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@pg:5432/$POSTGRES_DB
volumes:
  db:
